apiVersion: v1
kind: Service
metadata:
  name: backend-service-apigate
spec:
  selector:
    app: backend-apigate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - name: metrics          # <--- must match ServiceMonitor port
      port: 9100             # arbitrary cluster port for metrics
      targetPort: 8080
  type: ClusterIP